CREATE TABLE pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_completo VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    telefone VARCHAR(20),
    data_nascimento DATE,
    naturalidade VARCHAR(100),
    estado_civil VARCHAR(50),
    profissao VARCHAR(100),
    data_cadastro TIMESTAMP WITHOUT TIME ZONE,

    -- Campos do Endereco embutido
    rua VARCHAR(255),
    numero VARCHAR(20),
    bairro VARCHAR(100),
    cep VARCHAR(10),
    cidade VARCHAR(100),
    estado VARCHAR(50),
    
    PRIMARY KEY (id)
);